# Generated by Django 3.0.7 on 2020-06-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
