# Generated by Django 3.0.7 on 2020-06-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('horaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbPorte', models.IntegerField()),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.DateField()),
                ('marque', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
