# Generated by Django 3.0.7 on 2020-06-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0005_agence_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='annee',
        ),
    ]
