# Generated by Django 3.0.7 on 2020-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accueil', '0006_remove_vehicule_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='image',
            field=models.CharField(default='https://omegamma.com.au/wp-content/uploads/2017/04/default-image.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
